version: 2.1
jobs:
  build:
    parameters:
      output:
        type: string
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - run: echo "<< parameters.output >>"

workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            branches:
              only: master
          output: "i don't run by tag"
      - auto-semver/calculate-version:
          name: calculate_version
          current_branch: << pipeline.git.branch >>
  tagged-build:
    #when: << pipeline.parameters.version >>
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
              #only: /^v<< pipeline.parameters.version >>/
          output: "my tag is $CIRCLE_TAG" # run the `echo` command

parameters:
  version:
    type: string
    default: ""
