version: 2.1

jobs:
  build:
    parameters:
      output:
        type: string
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - run: echo "<< parameters.output >>"
  calculate-semver:
    docker:
      - image: circleci/node:14
    resource_class: small
    parameters:
      default_branch:
        type: string
        default: "master"
    steps:
      - checkout
      - run:
          name: Create package.json
          command: |
            FILE=package.json
            if [ -f "$FILE" ]; then
              echo "$FILE exists. Will skip it, please add @semantic-release/commit-analyzer the plugin to calculate semver."
            else 
              echo "The file $FILE does not exist, will create it."
              cat >$FILE \<<EOL
                {
                  "release": {
                    "plugins": [
                      "@semantic-release/commit-analyzer",
                      "@semantic-release/release-notes-generator",
                      "@semantic-release/github"
                    ],
                    "branch": "<< parameters.default_branch >>"
                  }
                }
            EOL
            fi
      - run: npm install
      - run: 
          name: Calculate semver 
          command: npx semantic-release 
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            branches:
              only: master
          output: "i don't run by tag"
      - calculate-semver
  tagged-build:
    #when: << pipeline.parameters.version >>
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
              #only: /^v<< pipeline.parameters.version >>/
            branches:
              ignore: /.*/
          output: "my tag is $CIRCLE_TAG" # run the `echo` command

parameters:
  version:
    type: string
    default: ""
